# Generated by Django 5.1.4 on 2025-04-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_order_city_alter_order_branch_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='city_ref',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='branch_number',
            new_name='warehouse_ref',
        ),
    ]
